'use strict';

/**
 * dump-schema — read-only snapshot of the live brain.db schema.
 *
 * Writes om-brain/db/SCHEMA-SNAPSHOT.md with sqlite_master DDL (tables,
 * indexes, triggers) and row counts per table. Safe to run repeatedly;
 * only the snapshot file is written.
 *
 * Usage:
 *   node scripts/dump-schema.js [--db <path>] [--out <path>]
 *
 * Environment:
 *   BRAIN_DB_PATH — overrides default db path (same as om-brain runtime)
 *
 * After deploy or seed:
 *   cd om-brain && node scripts/init-db.js          # if fresh DB
 *   node scripts/theology/seed-theology.sh          # optional theology seed
 *   node scripts/dump-schema.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DEFAULT_OUT = path.join(ROOT, 'db', 'SCHEMA-SNAPSHOT.md');

// Load production env when present (same pattern as seed-knowledge.js).
const prodEnv = '/etc/om-brain/om-brain.env';
if (!process.env.BRAIN_DB_PATH && fs.existsSync(prodEnv)) {
  for (const line of fs.readFileSync(prodEnv, 'utf8').split('\n')) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (m && process.env[m[1]] == null) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
}

const { config } = require('../src/config');

function parseArgs() {
  const argv = process.argv.slice(2);
  const opts = {
    dbPath: config.memory.dbPath,
    outPath: DEFAULT_OUT,
  };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--db' && argv[i + 1]) opts.dbPath = argv[++i];
    else if (argv[i] === '--out' && argv[i + 1]) opts.outPath = argv[++i];
    else if (argv[i] === '--help' || argv[i] === '-h') {
      process.stdout.write(
        'Usage: node scripts/dump-schema.js [--db <path>] [--out <path>]\n',
      );
      process.exit(0);
    }
  }
  if (!path.isAbsolute(opts.dbPath)) {
    opts.dbPath = path.resolve(ROOT, opts.dbPath);
  }
  if (!path.isAbsolute(opts.outPath)) {
    opts.outPath = path.resolve(ROOT, opts.outPath);
  }
  return opts;
}

function loadSqlite() {
  try {
    // eslint-disable-next-line global-require
    return require('better-sqlite3');
  } catch (err) {
    process.stderr.write(
      `[dump-schema] better-sqlite3 is required: ${err.message}\n`,
    );
    process.exit(1);
  }
}

function classifyObject(name, type, tblName) {
  if (type === 'table') return 'table';
  if (type === 'trigger') return 'trigger';
  if (type === 'index') {
    if (name.startsWith('sqlite_autoindex_')) return 'autoindex';
    return 'index';
  }
  return type;
}

function tableNames(db) {
  return db
    .prepare(
      `SELECT name FROM sqlite_master
       WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
       ORDER BY name`,
    )
    .all()
    .map((r) => r.name);
}

function rowCount(db, table) {
  try {
    const row = db.prepare(`SELECT COUNT(*) AS n FROM "${table.replace(/"/g, '""')}"`).get();
    return row.n;
  } catch (_) {
    return null;
  }
}

function objectsForTable(db, table) {
  return db
    .prepare(
      `SELECT type, name, tbl_name, sql
       FROM sqlite_master
       WHERE (type = 'table' AND name = ?)
          OR (type = 'index' AND tbl_name = ? AND name NOT LIKE 'sqlite_autoindex_%')
          OR (type = 'trigger' AND tbl_name = ?)
       ORDER BY
         CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END,
         name`,
    )
    .all(table, table, table);
}

function buildSnapshot(db, dbPath) {
  const generatedAt = new Date().toISOString();
  const tables = tableNames(db);
  const counts = {};
  let totalRows = 0;
  for (const t of tables) {
    const n = rowCount(db, t);
    counts[t] = n;
    if (typeof n === 'number') totalRows += n;
  }

  const lines = [];
  lines.push('# brain.db Schema Snapshot');
  lines.push('');
  lines.push(
    '> Auto-generated by `node om-brain/scripts/dump-schema.js`. **Do not edit manually.**',
  );
  lines.push(`> Generated: ${generatedAt}`);
  lines.push('');
  lines.push('Agents: **read this file at session start** for the live schema (columns, indexes, triggers, row counts).');
  lines.push('Canonical DDL source: `om-brain/db/schema.sql` (+ migrations if not yet merged).');
  lines.push('');
  lines.push('## Database');
  lines.push('');
  lines.push('| Property | Value |');
  lines.push('|----------|-------|');
  lines.push(`| Path | \`${dbPath}\` |`);
  lines.push(`| Tables | ${tables.length} |`);
  lines.push(`| Total rows | ${totalRows} |`);
  lines.push('');
  lines.push('## Row counts');
  lines.push('');
  lines.push('| Table | Rows |');
  lines.push('|-------|------:|');
  for (const t of tables) {
    const n = counts[t];
    lines.push(`| ${t} | ${n == null ? '—' : n} |`);
  }
  lines.push('');

  for (const table of tables) {
    const n = counts[table];
    const label = n == null ? table : `${table} (${n} rows)`;
    lines.push(`## ${label}`);
    lines.push('');

    const objects = objectsForTable(db, table);
    for (const obj of objects) {
      const kind = classifyObject(obj.name, obj.type, obj.tbl_name);
      if (kind === 'autoindex') continue;
      if (!obj.sql) continue;
      lines.push(`### ${obj.type}: \`${obj.name}\``);
      lines.push('');
      lines.push('```sql');
      lines.push(obj.sql.trim());
      lines.push('```');
      lines.push('');
    }
  }

  // Catch orphan indexes/triggers (e.g. vec virtual tables)
  const covered = new Set(tables);
  const extras = db
    .prepare(
      `SELECT type, name, tbl_name, sql FROM sqlite_master
       WHERE type IN ('table', 'index', 'trigger')
         AND name NOT LIKE 'sqlite_%'
         AND (tbl_name IS NULL OR tbl_name NOT IN (${tables.map(() => '?').join(', ') || "''"}))
       ORDER BY type, name`,
    )
    .all(...tables);

  if (extras.length) {
    lines.push('## Other schema objects');
    lines.push('');
    for (const obj of extras) {
      if (!obj.sql) continue;
      lines.push(`### ${obj.type}: \`${obj.name}\`${obj.tbl_name ? ` (on \`${obj.tbl_name}\`)` : ''}`);
      lines.push('');
      lines.push('```sql');
      lines.push(obj.sql.trim());
      lines.push('```');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function main() {
  const opts = parseArgs();
  if (!fs.existsSync(opts.dbPath)) {
    process.stderr.write(
      `[dump-schema] database not found: ${opts.dbPath}\n` +
        '[dump-schema] Run `node scripts/init-db.js` first, or pass --db <path>.\n',
    );
    process.exit(1);
  }

  const Sqlite = loadSqlite();
  const db = new Sqlite(opts.dbPath, { readonly: true, fileMustExist: true });
  try {
    const markdown = buildSnapshot(db, opts.dbPath);
    fs.mkdirSync(path.dirname(opts.outPath), { recursive: true });
    fs.writeFileSync(opts.outPath, markdown, 'utf8');
    process.stdout.write(`[dump-schema] wrote ${opts.outPath}\n`);
  } finally {
    db.close();
  }
}

main();
